[package]
name = "dnd"
version = "0.1.0"
edition = "2021"

[dependencies]
iced ={ git = "https://github.com/iced-rs/iced.git", features = ["markdown"]} 
pdf_forms = {git = "https://github.com/Emulator000/pdf_form.git"}
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
